# Generated by Django 6.0.1 on 2026-05-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplimentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='credit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('credit', 'Credit'), ('paid', 'Paid')], default='credit', max_length=20),
        ),
    ]
