# Generated by Django 6.0.1 on 2026-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplimentApp', '0002_orders_credit_price_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='bottle_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='loose_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity_status',
            field=models.CharField(choices=[('bottle', 'Bottle'), ('loose', 'Loose')], default='bottle', max_length=20),
        ),
    ]
