# Generated by Django 6.0.1 on 2026-06-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplimentApp', '0003_orders_bottle_quantity_orders_loose_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='loose_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
